# Generated by Django 5.1.4 on 2024-12-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapdrive_app', '0002_alter_trip_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle_data',
            name='cheapdrive_app_vehicle_data_cur_fuel_lte_tank_size',
        ),
        migrations.AddConstraint(
            model_name='vehicle_data',
            constraint=models.CheckConstraint(condition=models.Q(('cur_fuel__lte', models.F('tank_size'))), name='cur_fuel_lte_tank_size'),
        ),
    ]
