# Generated by Django 5.1.4 on 2024-12-28 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_alter_vehicle_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_data',
            name='guest_session_id',
        ),
        migrations.RemoveField(
            model_name='vehicle_data',
            name='user',
        ),
        migrations.AddField(
            model_name='vehicle_data',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.trip'),
        ),
    ]
