# Generated by Django 5.1.4 on 2024-12-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_remove_vehicle_data_guest_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_data',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='Vehicle_data',
        ),
    ]
