# Generated by Django 5.1.4 on 2024-12-31 12:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_address', models.CharField(max_length=255)),
                ('finishing_address', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=1, help_text='Distance of trip', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duration of the trip - in minutes', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_size', models.DecimalField(decimal_places=2, help_text="The size of the vehicle's fuel tank in liters.", max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel_type', models.CharField(choices=[('D', 'Diesel'), ('P', 'Pb95')], help_text='The type of fuel used by the vehicle.', max_length=3)),
                ('cur_fuel', models.DecimalField(decimal_places=2, help_text='The current amount of fuel in the tank in liters.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fuel_consumption_per_100km', models.DecimalField(decimal_places=2, help_text="The vehicle's fuel consumption in liters per kilometer.", max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_of_fuel', models.DecimalField(decimal_places=2, help_text='The price the stored gas was purchased for.', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currency', models.CharField(default='PLN', help_text='The currency of the purchase price.', max_length=3)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refill.trip')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('cur_fuel__lte', models.F('tank_size'))), name='cur_fuel_lte_tank_size')],
            },
        ),
    ]
