# Generated by Django 5.1.4 on 2024-12-31 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_data',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_data', to='refill.trip'),
        ),
    ]
