# Generated by Django 5.1.4 on 2025-01-03 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0002_alter_vehicle_data_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(default='PLN', help_text='The currency of the trip price.', max_length=3),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of the trip', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
