# Generated by Django 5.1.4 on 2025-01-03 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0003_trip_currency_trip_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_data',
            name='price_of_fuel',
            field=models.DecimalField(decimal_places=2, help_text='The price the stored gas was purchased for.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
