# Generated by Django 5.1.4 on 2025-01-03 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0006_alter_vehicle_data_price_of_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price of the trip', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
