# Generated by Django 5.1.4 on 2025-01-05 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0008_remove_trip_currency_remove_trip_trip_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_data',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who owns the vehicle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
